### ISSUE TITLE
I am in China, Shanghai right now

### ISSUE THREAD

**Issue by revusky** [jdbcx/jdbcx#64]
Hi. I am sorry to use this channel of communication. I thought to tell you that I am in China, Shanghai right now. I sent you an email to your gmail address but I have the feeling you never saw it. My phone number is ***. My wechat is: ***

Jonathan Revusky, lead developer CongoCC project

**Comment by zhicwu** [comment]
I must miss your email as I don't check email often. Just masked your mobile phone number and wechat. Will call you after getting back to home.
