### ISSUE TITLE
How to use in ClickHouse url function?

### ISSUE THREAD

**Issue by ruslanen** [jdbcx/jdbcx#65]
Hi @zhicwu, thank you for your jdbc-bridge and jdbcx!

I try to send some SELECT queries into ClickHouse and get an error:
```
Code: 86. DB::HTTPException: Received error from remote server /query?q={{db(url=jdbc:postgresql://ip:5432/microsoft_contoso_integration_100k?user=postgres&password=):select%1}}. HTTP status code: 400 Bad Request, body: <h1>400 Bad Request</h1>URISyntaxException thrown: While executing ParallelParsingBlockInputFormat: While executing URL. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER) (version 23.3.4.17 (official build)) , server ClickHouseNode [uri=http://localhost:8124/default, options={socket_timeout=3000000,custom_http_params=session_id=DataGrip_a5b3082a-1a1b-477a-8948-6a6f42240cb0}]@639965262
```

Query:
```
SELECT *
FROM url('http://host.docker.internal:8080/query?q={{db(url=jdbc:postgresql://ip:5432/microsoft_contoso_integration_100k?user=postgres&password=):select%1}}', LineAsString)
```
I've already read readme and some part of code,  but it looks like there's an error on the CH side.
In curl it works fine.
What's wrong with it?

**Comment by ruslanen** [comment]
Thanks for the answer.
Is your query just an example? I don't understand what the `1.csv` has to do with it.
I got:
```
 HTTP status code: 404 Not Found, body: : While executing ParallelParsingBlockInputFormat: While executing URL. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER) (version 23.3.4.17 (official build)) , server ClickHouseNode [uri=http://localhost:8124/default, options={socket_timeout=3000000,custom_http_params=session_id=DataGrip_98fb4ee9-3194-486e-a0bc-70fc015f71cc}]@1200390399
```

**Comment by zhicwu** [comment]
Apologize for the confusion earlier😂. The correct URL should include `q=` as part of the query string, similar to the example below.
```
SELECT *
FROM url('http://host.docker.internal:8080/query?q=%7B%7Bdb%28url%3Djdbc%3Apostgresql%3A%2F%2Fip%3A5432%2Fmicrosoft_contoso_integration_100k%3Fuser%3Dpostgres%26password%3D%29%3Aselect%2B1%7D%7D', CSVWithNames, '<column definitions>')
```

JDBCX supports multiple [query modes](https://github.com/jdbcx/jdbcx/blob/main/driver/src/main/java/io/github/jdbcx/QueryMode.java). `/1.csv` is similar to `/query`, except that it uses a hard-coded query ID `1` and returns the response in `CSV` format(with headers by default). Query ID is particular useful when you want to execute a query in async mode, for example:
1. Initiate an asynchronous query from one process: `http://bridge-server/async/123.jsonl?q=select+1`
2. and then retrieve the result in another process by accessing `http://bridge-server/123.jsonl`

**Comment by ruslanen** [comment]
Thanks for your help!
